// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSe884ENPOd8zGals-0UyX-wgPfldNMew',
    appId: '1:209376647040:web:6eb9c97f9e065eafa05365',
    messagingSenderId: '209376647040',
    projectId: 'jotrip-signin',
    authDomain: 'jotrip-signin.firebaseapp.com',
    storageBucket: 'jotrip-signin.appspot.com',
    measurementId: 'G-CSV582MNMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqbqefksLoQNVNtORz8Z6r5C0uFncAJY',
    appId: '1:209376647040:android:fdb0925141ab5b4aa05365',
    messagingSenderId: '209376647040',
    projectId: 'jotrip-signin',
    storageBucket: 'jotrip-signin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3zE8yHZ0c2pF-eyt4OH2j_8HrujZKnI',
    appId: '1:209376647040:ios:ba5378259390f2b9a05365',
    messagingSenderId: '209376647040',
    projectId: 'jotrip-signin',
    storageBucket: 'jotrip-signin.appspot.com',
    iosBundleId: 'com.example.jotrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU3zE8yHZ0c2pF-eyt4OH2j_8HrujZKnI',
    appId: '1:209376647040:ios:ba5378259390f2b9a05365',
    messagingSenderId: '209376647040',
    projectId: 'jotrip-signin',
    storageBucket: 'jotrip-signin.appspot.com',
    iosBundleId: 'com.example.jotrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSe884ENPOd8zGals-0UyX-wgPfldNMew',
    appId: '1:209376647040:web:628a85fb3e59b3f7a05365',
    messagingSenderId: '209376647040',
    projectId: 'jotrip-signin',
    authDomain: 'jotrip-signin.firebaseapp.com',
    storageBucket: 'jotrip-signin.appspot.com',
    measurementId: 'G-7X3XL8Q8VM',
  );
}
